version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gib6
      POSTGRES_DB: dbpersonel
    ports:
     - "5432:5432"
    volumes:
     - pgdata:/var/lib/postgresql/data
    networks:
     - spring-network

  springboot-app:
    build: .
    container_name: springboot-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - spring-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: zcanarif@gmail.com
      PGADMIN_DEFAULT_PASSWORD: gib6
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - spring-network

volumes:
  pgdata:

networks:
 spring-network: